[package]
name = "fdb-c"
version = "0.1.0"
edition = "2021"

[features]
510 = []
520 = []
600 = []
610 = []
620 = []
630 = []
700 = []
710 = []
730 = []


[dependencies]

[build-dependencies]
bindgen = "0.69.4"
cfg-if = "1.0.0"